# Local dev conda dependencies
channels:
- mattkram
- mattkram/label/dev
- conda-forge
dependencies:
- python=3.10
- lembas
- reef3d
- jinja2
- pandas
- xarray
- matplotlib
- pytables
- scipy
- pip
- pip:
  - "-e ."
